# Generated by Django 2.1.5 on 2019-01-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_like', models.BooleanField()),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='DepartmentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='ExpertReviewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default=None, max_length=250)),
                ('f_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.AnswersModel')),
            ],
            options={
                'db_table': 'expert_reviews',
            },
        ),
        migrations.CreateModel(
            name='GradesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=60)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='SectionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='StepsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=60)),
                ('f_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='answers.SectionsModel')),
            ],
            options={
                'db_table': 'steps',
            },
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='f_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='answers.StepsModel'),
        ),
        migrations.AddField(
            model_name='expertreviewsmodel',
            name='f_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='answers.GradesModel'),
        ),
    ]
