# Generated by Django 2.1.5 on 2019-01-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreviewsmodel',
            name='f_user_expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.UsersModel'),
        ),
        migrations.AddField(
            model_name='answersmodel',
            name='f_expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='f_expert', to='users.UsersModel'),
        ),
        migrations.AddField(
            model_name='answersmodel',
            name='f_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='answers.GradesModel'),
        ),
        migrations.AddField(
            model_name='answersmodel',
            name='f_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='answers.QuestionsModel'),
        ),
        migrations.AddField(
            model_name='answersmodel',
            name='f_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_user', to='users.UsersModel'),
        ),
    ]
