# Generated by Django 2.1.5 on 2019-02-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allActions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='department',
            field=models.ManyToManyField(to='allActions.DepartmentsModel'),
        ),
    ]
