# Generated by Django 2.1.5 on 2019-02-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allActions', '0002_questionsmodel_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsmodel',
            old_name='f_step',
            new_name='f_stage',
        ),
    ]
