# Generated by Django 2.1.5 on 2019-02-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allActions', '0003_auto_20190201_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='hint',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
